# Generated by Django 3.0.3 on 2020-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=50)),
                ('courseNo', models.CharField(max_length=15)),
                ('discipline1', models.CharField(choices=[('PC', 'Programming - C++'), ('PP', 'Programming - Python'), ('GD', 'Game Development'), ('DA', 'Data Structures and Algorithms'), ('CO', 'Computer Organization'), ('OS', 'Operating Systems'), ('PL', 'Programming Languages'), ('CS', 'Cybersecurity'), ('MA', 'Mobile Applications'), ('AI', 'Artificial Intelligence'), ('NT', 'Networks'), ('TC', 'Theory of Computation'), ('PD', 'Parallel and Distributed Systems'), ('', '--------')], default='', max_length=2)),
                ('discipline2', models.CharField(choices=[('PC', 'Programming - C++'), ('PP', 'Programming - Python'), ('GD', 'Game Development'), ('DA', 'Data Structures and Algorithms'), ('CO', 'Computer Organization'), ('OS', 'Operating Systems'), ('PL', 'Programming Languages'), ('CS', 'Cybersecurity'), ('MA', 'Mobile Applications'), ('AI', 'Artificial Intelligence'), ('NT', 'Networks'), ('TC', 'Theory of Computation'), ('PD', 'Parallel and Distributed Systems'), ('', '--------')], default='', max_length=2)),
            ],
        ),
    ]
