# Generated by Django 3.0.3 on 2020-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADTAA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseNo',
            new_name='courseNumber',
        ),
        migrations.AddField(
            model_name='course',
            name='courseDays',
            field=models.CharField(choices=[('MW', 'MW'), ('TR', 'TR')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='courseTime',
            field=models.IntegerField(choices=[(1, '08:00 AM - 09:15 AM'), (2, '09:25 AM - 10:40 AM'), (3, '10:50 AM - 12:05 PM'), (4, '12:15 PM - 01:30 PM'), (5, '01:40 PM - 02:55 PM'), (6, '03:05 PM - 04:20 PM'), (7, '04:30 PM - 05:45 PM')], default=0),
        ),
    ]
