# Generated by Django 3.0.3 on 2020-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=50)),
                ('courseNo', models.CharField(max_length=15)),
                ('discipline1', models.CharField(choices=[('PC', 'Programming - C+'), ('AI', 'Artificial Intelligence'), ('CS', 'Cybersecurity'), ('PP', 'Programming - Python'), ('PL', 'Programming Languages'), ('OS', 'Operating Systems')], default=None, max_length=2)),
                ('discipline2', models.CharField(choices=[('PC', 'Programming - C+'), ('AI', 'Artificial Intelligence'), ('CS', 'Cybersecurity'), ('PP', 'Programming - Python'), ('PL', 'Programming Languages'), ('OS', 'Operating Systems')], default=None, max_length=2)),
            ],
        ),
    ]
